[package]
name = "counter"
version = "0.1.0"
edition = "2021"

[dependencies]
kabto   = { path = ".." }
web-sys = { version = "0.3", features = ["Window", "Document", "Element", "Text", "console"] }

[features]
DEBUG = ["kabto/DEBUG"]